name: esp32
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  firebase_auth:
  firebase_database:
  flutter_riverpod:
  riverpod_annotation:
  email_validator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner:
  riverpod_generator:

flutter:
  uses-material-design: true
